"""empty message

Revision ID: 782c76c897d3
Revises: 3271ad5503d0
Create Date: 2026-03-24 15:09:07.552871

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '782c76c897d3'
down_revision = '3271ad5503d0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('character', schema=None) as batch_op:
        batch_op.add_column(sa.Column('population', sa.Integer(), nullable=False))
        batch_op.drop_column('mass')

    with op.batch_alter_table('planet', schema=None) as batch_op:
        batch_op.add_column(sa.Column('population', sa.Integer(), nullable=False))
        batch_op.drop_column('mass')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('planet', schema=None) as batch_op:
        batch_op.add_column(sa.Column('mass', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.drop_column('population')

    with op.batch_alter_table('character', schema=None) as batch_op:
        batch_op.add_column(sa.Column('mass', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.drop_column('population')

    # ### end Alembic commands ###
